# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python
trigger:
  tags:
    include:
      - v*

pr: none

stages:
- stage: build
  jobs:
  - job: build
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - script: |    
        docker run -v "$PWD":/var/task "lambci/lambda:build-python3.7" /bin/sh -c "pip install -r requirements.txt -t python/lib/python3.7/site-packages/; exit"
        docker run -v "$PWD":/var/task "lambci/lambda:build-python3.8" /bin/sh -c "pip install -r requirements.txt -t python/lib/python3.8/site-packages/; exit"
      displayName: 'install requirements'
    - task: CopyFiles@2
      inputs:
        contents: 'python/**'
        targetFolder: $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'dist'
        publishLocation: 'Container'
    
- stage: deploy_github_release
  dependsOn: build
  jobs:
  - job: deploy_github_release
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: dist        
        path: $(Build.ArtifactStagingDirectory)
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/pycfdi-transform-aws-lambda-layer-$(Build.SourceVersion).zip'
        replaceExistingArchive: true
    - task: GitHubRelease@1
      inputs:
        gitHubConnection: 'github.com_hermesjimenez'
        repositoryName: 'swsapien/pycfdi-transform-aws-lambda-layer'
        action: 'create'
        target: '$(Build.SourceVersion)'
        tagSource: 'gitTag'
        changeLogCompareToRelease: 'lastFullRelease'
        changeLogType: 'commitBased'
        assets: |
          $(Build.ArtifactStagingDirectory)/pycfdi-transform-aws-lambda-layer-$(Build.SourceVersion).zip